### ISSUE TITLE
gif crashes the program

### ISSUE THREAD

**Issue by benni347** [Tatsh/patreon-archiver#124]
I am archiving some posts of a creator, the creator requalry uploads gifs. It crashes since it is not defined in the metadata type.
```

Traceback (most recent call last):
  File "/home/username/.local/bin/patreon-archiver", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/patreon_archiver/main.py", line 173, in main
    media_uris = list(
                 ^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/patreon_archiver/main.py", line 173, in <genexpr>
    media_uris = list(
                     ^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/patreon_archiver/main.py", line 85, in process_posts
    yield from save_images(session, post)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/patreon_archiver/main.py", line 54, in save_images
    + get_extension(data["attributes"]["mimetype"])
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/patreon-archiver/lib/python3.12/site-packages/patreon_archiver/utils.py", line 34, in get_extension
    raise UnknownMimetypeError(mimetype)
patreon_archiver.utils.UnknownMimetypeError: image/gif
```

To fix this add, to the utils.py file get file ext function this
```
if mimetype == 'image/gif':
        return 'gif'
```

**Comment by Tatsh** [comment]
Can you make a PR?
